server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/keepguard_api_db
    username: keepguard_api_user
    password: keepguard_api_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000
  data:
    redis:
      cluster:
        nodes: redis-node-1:7000,redis-node-2:7001,redis-node-3:7002,redis-node-4:7003,redis-node-5:7004,redis-node-6:7005
        max-redirects: 3
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_schema: ms_user

logging:
    port: 5000
    enabled: true
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
    com.keepguard.ms_user: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

cache:
  redis:
    ttl:
      user: 2592000     # 30 dias
      notify: 2592000   # 30 dias
      register_session: 1200  # 20 minutos
    prefix:
      user: "user_cache"
      notify: "notify_cache"
      register: "register_session"
    max_attempts:
      register_token: 5  # máximo de tentativas de validação de token

keepguard:
  audit:
    exchange: srv-audit-exchange-prod